# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200225_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '作者')], default=0),
        ),
    ]
